### ISSUE TITLE
getWeather is not a function

### ISSUE THREAD

**Issue by jschmidtnj** [JonahMania/Oswald#1]
TypeError: weather.getWeather is not a function
    at Oswald.onMessage (/home/stevensultimateducks/Oswald/src/oswald.js:226:29)

It is required and imported correctly, so I do not understand what is going on.

**Comment by JonahMania** [comment]
So i think the problem is that you don't export the getWeather function in src/weather/index.js. For example look at  https://github.com/JonahMania/Oswald/blob/master/src/lines/index.js#L149. I think you just need to add the line module.exports.getWeather = getWeather; to the bottom of your index file. Let me know if that works.

**Comment by jschmidtnj** [comment]
everything works now - you were right
